# Generated by Django 3.2.9 on 2021-12-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='image',
            field=models.FileField(upload_to='detail/'),
        ),
    ]
